[local]
host=10.1.1.17
port=5432
dbname=postgres
user=postgres

[authelia]
host=10.1.1.17
port=5432
dbname=authelia
user=authelia

[gitea]
host=10.1.1.17
port=5432
dbname=gitea
user=gitea

[immich]
host=10.1.1.17
port=5432
dbname=immich
user=immich

[memos]
host=10.1.1.17
port=5432
dbname=memos
user=memos

[umami]
host=10.1.1.17
port=5432
dbname=umami
user=umami

[vaultwarden]
host=10.1.1.17
port=5432
dbname=vaultwarden
user=vaultwarden

[zabbix]
host=10.1.1.17
port=5432
dbname=zabbix
user=zabbix

#[dev]
#host=dev-db.internal
#port=5432
#dbname=myapp_dev
#user=troy

#[prod]
#host=prod-db.internal
#port=5432
#dbname=myapp_prod
#user=troy
#sslmode=require
