[local]
host=10.1.1.17
port=5432
dbname=postgres
user=postgres

#[dev]
#host=dev-db.internal
#port=5432
#dbname=myapp_dev
#user=troy
#
#[prod]
#host=prod-db.internal
#port=5432
#dbname=myapp_prod
#user=troy
#sslmode=require
