" Set defaults for XDG environment variables if not defined
if empty($XDG_STATE_HOME)
  let $XDG_STATE_HOME = $HOME.'/.local/state'
endif
if empty($XDG_DATA_HOME)
  let $XDG_DATA_HOME = $HOME.'/.local/share'
endif

" Create all necessary directories
call mkdir($XDG_STATE_HOME.'/vim/backup', 'p')
call mkdir($XDG_STATE_HOME.'/vim/swap', 'p')
call mkdir($XDG_STATE_HOME.'/vim/undo', 'p')
call mkdir($XDG_STATE_HOME.'/vim/view', 'p')
call mkdir($XDG_DATA_HOME.'/vim/spell', 'p')

" Set directory paths
set backupdir=$XDG_STATE_HOME/vim/backup
set directory=$XDG_STATE_HOME/vim/swap
set undodir=$XDG_STATE_HOME/vim/undo
set viewdir=$XDG_STATE_HOME/vim/view
set viminfofile=$XDG_STATE_HOME/vim/viminfo

" Configure netrw home directory
let g:netrw_home = $XDG_DATA_HOME."/vim"

" Enable file safety features
set undofile
set writebackup
set backup
set backupcopy=yes

" Appearance
colorscheme nord
set number
set cursorline
set laststatus=2
set noshowmode
set nowrap
set showmatch
set scrolloff=3

" Lightline statusline configuration
let g:lightline = {
  \ 'colorscheme': 'nord',
  \ 'separator': { 'left': "\ue0b0", 'right': "\ue0b2" },
  \ 'subseparator': { 'left': "\ue0b1", 'right': "\ue0b3" }
  \ }

" Indentation and tabs
set autoindent
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4

" General settings
set encoding=UTF-8
set history=10000
set timeoutlen=500
set clipboard=unnamed,unnamedplus
set mouse=a

" Search settings
set ignorecase smartcase
set incsearch hlsearch

" Command-line completion
set wildmenu wildmode=list:longest
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx,*.DS_Store

" Leader key
let mapleader = " "

" NERDTree configuration
let NERDTreeRespectWildIgnore=1
let NERDTreeShowHidden=1
let NERDTreeQuitOnOpen=1

" Key mappings
map <leader>ee :NERDTreeToggle<CR>
map <leader>ff :Files<CR>
map <leader>fr :History<CR>
map <leader>nn :set number!<CR>
map <leader>ss :setlocal spell! spelllang=en_gb<CR>
map <leader><space> :nohlsearch<CR>
nmap <leader>c <Plug>OSCYankOperator
nmap <leader>cc <leader>c_
vmap <leader>c <Plug>OSCYankVisual
