" Set defaults for XDG environment variables if not defined
if empty($XDG_CONFIG_HOME)
  let $XDG_CONFIG_HOME = $HOME.'/.config'
endif
if empty($XDG_DATA_HOME)
  let $XDG_DATA_HOME = $HOME.'/.local/share'
endif
if empty($XDG_STATE_HOME)
  let $XDG_STATE_HOME = $HOME.'/.local/state'
endif

" Configure XDG-compliant paths
set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

" Set packpath for Vim 8.0+ (plugin management)
if exists('&packpath')
  set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
  set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after
endif

" Configure netrw home directory
let g:netrw_home = $XDG_DATA_HOME."/vim"

" Create base vim data directory
if !isdirectory($XDG_DATA_HOME."/vim")
  call mkdir($XDG_DATA_HOME."/vim", 'p')
endif

" Create and set directory paths (using the clever pattern from older version)
set backupdir=$XDG_STATE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_STATE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_STATE_HOME/vim/undo     | call mkdir(&undodir, 'p')
set viewdir=$XDG_STATE_HOME/vim/view     | call mkdir(&viewdir, 'p')

" Create spell directory
call mkdir($XDG_DATA_HOME."/vim/spell", 'p')

" Set viminfo file location
set viminfofile=$XDG_STATE_HOME/vim/viminfo

" Enable file safety features
set undofile
set writebackup
set backup
set backupcopy=yes

" Appearance
colorscheme nord
set number
set cursorline
set laststatus=2
set noshowmode
set nowrap
set showmatch
set scrolloff=3

" Lightline statusline configuration
let g:lightline = {
  \ 'colorscheme': 'nord',
  \ 'separator': { 'left': "\ue0b0", 'right': "\ue0b2" },
  \ 'subseparator': { 'left': "\ue0b1", 'right': "\ue0b3" }
  \ }

" Indentation and tabs
set autoindent
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4

" General settings
set encoding=UTF-8
set history=10000
set timeoutlen=500
set clipboard=unnamed,unnamedplus
set mouse=a

" Search settings
set ignorecase smartcase
set incsearch hlsearch

" Command-line completion
set wildmenu wildmode=list:longest
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx,*.DS_Store

filetype plugin indent on
syntax on

" Leader key
let mapleader = " "

" NERDTree configuration
let NERDTreeRespectWildIgnore=1
let NERDTreeShowHidden=1
let NERDTreeQuitOnOpen=0

" Key mappings
map <leader>ee :NERDTreeToggle<CR>
map <leader>ff :Files<CR>
map <leader>fr :History<CR>
map <leader>nn :set number!<CR>
map <leader>ss :setlocal spell! spelllang=en_gb<CR>
map <leader><space> :nohlsearch<CR>
nmap <leader>c <Plug>OSCYankOperator
nmap <leader>cc <leader>c_
vmap <leader>c <Plug>OSCYankVisual
